/*SORT*/


/*JS CREADO PARA LA SECCIÓN COMERCIOS A LA CUAL SE PODRÁ ACCEDER DESDE EL INDEX (INICIO). POR EL MOMENTO NO HE PROGRAMADO EL HTML Y CSS DE LAS SECCIONES DE CADA COMERCIO RESPECTIVO, A LOS EFECTOS DE LA SEGUNDA PRE-ENTREGA Y TRATANDO DE NUCLEAR LOS TEMAS VISTOS VOY PRESENTADO ALGO DEL JS QUE TENDRÁN ESTAS SECCIONES*/


const numeros = [10, 20, 30, 40];
numeros.sort((a,b) => a - b);
console.log(numeros);

numeros.sort((a,b) => b - a);
console.log(numeros);

